name: ArchonBot
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies:
  html: ^0.15.2
  http: ^0.13.5
  image: ^4.0.15
  markdown: ^7.0.2
  sqlite3: ^1.11.0
  system_info: ^1.0.1
  teledart: ^0.5.6
